### ISSUE TITLE
It seems not work for multiple packages

### ISSUE THREAD

**Issue by zmtzawqlp** [Fly-Mix/flutter_r_demo#1]
it only works for pubspec.yaml in root, my project has many modules(packages)

**Comment by YK-Unit** [comment]
Flr now only works for one Flutter App/Module/Plugin/Package project, does not support for multiple projects. 

If you want to specify assets and generate r.g.dart for every package project,  you can install [Flr CLI Tool](https://github.com/Fly-Mix/flr-cli), then run the commands of flr-cli in each package project's root directory.

**Comment by zmtzawqlp** [comment]
more suggestion, in fact, you can read pubspec.yaml in root ,and find local dependencies packages and do the same thing for each packages .  one simple command is what we need.

something like  [ff_annotation_route](https://github.com/fluttercandies/ff_annotation_route)

**Comment by YK-Unit** [comment]
> more suggestion, in fact, you can read pubspec.yaml in root ,and find local dependencies packages and do the same thing for each packages . one simple command is what we need.
> 
> something like [ff_annotation_route](https://github.com/fluttercandies/ff_annotation_route)

Thanks for your suggestion !!!

We will  arrange to support for this feature that supports multiple sub-projects later.
